language: ruby
rvm:
- 2.3
cache: bundler
sudo: false
notifications:
  email: false
  hipchat:
    rooms:
      secure: XTt8ignRLzyF8QDD+tQdUazPhdIXLlbaFL+0hnpp6X/VV+n578U7h8eqWWa0/YnvL3E6j0auq61kpxgc2/H18T9euYh7o0QthbmKRYu7PV0QU+IUUH1z4N4V8IkvmM0RyQZvYnhtudbry47J5IojCv90x4/YMOjHPW4SB17ENxg=
  template:
  - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
  notify: true
deploy:
  provider: rubygems
  api_key:
    secure: zHLiJny/KS7dnCuXsCWKUtPgcl7ju34KCuxw8CAV4bhkw38BEokuxn0abwqvovYztvWFxz/0TYIzmVLFxwlqelhdTl+0ab8YigTlArYfzsToCxD/yH4ejM9PxL90/XO9Z/9AhKdXnZUGCE2UuGg7jnONh1KEYuCiz1F0zpViTHM=
  gem: routes_revealer
  on:
    branch: master
    repo: careerbuilder/routes-revealer
